on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.19.1
      - name: Run tests
        working-directory: ./frontend
        run: |
          npm ci
          npm run test

  build_and_publish_docker_image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username boringjpg --password ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build . --tag boringjpg/space-tracker:latest
          docker push boringjpg/space-tracker:latest
  