name: Node CI

on: [push, pull_request]

defaults:
    run:
        working-directory: ./frontend

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 18.19.1
            - run: npm ci
            - run: npm run test
  